### ISSUE TITLE
Collaborators needed / handover this lib.

### ISSUE THREAD

**Issue by richp10** [richp10/discourse-api-php#11]
I am finally abandoning PHP and am porting my discourse interaction to Go - so will probably not be using or developing this library further. 

Though it does not have many users - it is useful to those of you who find it useful.  I don't know how to hand over the repo entirely to someone else - could find out - but might easier to just make the three of you who have submitted PRs all collaborators.  It is a trivial library in many respects, but with time there are many more useful endpoints to add. 

So I have sent invites to..  @ajimix @nivshah @martinduparc 

Let me know if there is anything else I can do to help you to take this thing forward..

**Comment by nivshah** [comment]
Happy to help on this, I use this API to integrate a site I work on with a Discourse community and am kind of beholden to the language (not great, I know) so happy to do anything I can to help out.

**Comment by ajimix** [comment]
@richp10 thanks for the invitation. I'm also happy to help on this as I'm still using this library
