### ISSUE TITLE
Error from packlist

### ISSUE THREAD

**Issue by richp10** [richp10/discourse-api-php#15]
I got the following email from packlist.org

The richp10/discourse-api-php package of which you are a maintainer has
failed to update due to invalid data contained in your composer.json.
Please address this as soon as possible since the package stopped updating.

It is recommended that you use `composer validate` to check for errors when you
change your composer.json.

Below is the full update log which should highlight errors as
"Skipped branch ...":

[Composer\Repository\InvalidRepositoryException]: Some branches contained invalid data and were discarded, it is advised to review the log and fix any issues present in branches

Reading composer.json of richp10/discourse-api-php (1.2)
Importing tag 1.2 (1.2.0.0)
Reading composer.json of richp10/discourse-api-php (catfeature)
Importing branch catfeature (dev-catfeature)
Reading composer.json of richp10/discourse-api-php (master)
Importing branch master (dev-master)
Skipped branch master, Invalid package information: 
License "GPL2" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.
If the software is closed-source, you may use "proprietary" as license.

**Comment by ajimix** [comment]
Seems like license identifier is not correct. I've created a [PR](https://github.com/richp10/discourse-api-php/pull/16) to fix it
